// Generated by scripts/generate-historical-data.mjs
export const historicalDistricts = [
  {
    "districtId": "albert-park",
    "districtName": "Albert Park",
    "alpTpp2022": 61.150600869342895,
    "coalitionTpp2022": 38.8493991306571,
    "tppFormalVotes2022": 39110,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 62.5,
        "alpEnd": 59.69,
        "alpSwing": -2.8100000000000014,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 59.68632893823733,
        "alpEnd": 52.05579291279216,
        "alpSwing": -7.630536025445178,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 50.9,
        "alpEnd": 52.9582239720035,
        "alpSwing": 2.0582239720035034,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 52.9582239720035,
        "alpEnd": 63.12818325513712,
        "alpSwing": 10.169959283133611,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 63.1,
        "alpEnd": 61.150600869342895,
        "alpSwing": -1.9493991306571061,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "ashwood",
    "districtName": "Ashwood",
    "alpTpp2022": 56.15298590919258,
    "coalitionTpp2022": 43.84701409080742,
    "tppFormalVotes2022": 44710,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 52,
        "alpEnd": 56.15298590919258,
        "alpSwing": 4.15298590919258,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bass",
    "districtName": "Bass",
    "alpTpp2022": 50.24393778378901,
    "coalitionTpp2022": 49.75606221621099,
    "tppFormalVotes2022": 41404,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 49.36,
        "alpEnd": 44.48,
        "alpSwing": -4.880000000000001,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 44.47609472743521,
        "alpEnd": 37.41502723630307,
        "alpSwing": -7.061067491132144,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 37.6,
        "alpEnd": 45.448593659507,
        "alpSwing": 7.848593659506998,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 45.448593659507,
        "alpEnd": 52.394684304986995,
        "alpSwing": 6.946090645479996,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49.3,
        "alpEnd": 50.24393778378901,
        "alpSwing": 0.9439377837890106,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bayswater",
    "districtName": "Bayswater",
    "alpTpp2022": 54.22897251109181,
    "coalitionTpp2022": 45.77102748890819,
    "tppFormalVotes2022": 42599,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 52.739999999999995,
        "alpEnd": 47.11,
        "alpSwing": -5.629999999999996,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 47.107309001217644,
        "alpEnd": 39.42723342939482,
        "alpSwing": -7.680075571822831,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 43.2,
        "alpEnd": 45.3754878591822,
        "alpSwing": 2.1754878591822013,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 45.3754878591822,
        "alpEnd": 50.388186539369464,
        "alpSwing": 5.012698680187261,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49.4,
        "alpEnd": 54.22897251109181,
        "alpSwing": 4.828972511091813,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bellarine",
    "districtName": "Bellarine",
    "alpTpp2022": 58.46287616906666,
    "coalitionTpp2022": 41.53712383093334,
    "tppFormalVotes2022": 47153,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 58.25,
        "alpEnd": 57.95,
        "alpSwing": -0.30000000000000027,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 57.94885598923284,
        "alpEnd": 51.36520057270604,
        "alpSwing": -6.583655416526801,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 47.5,
        "alpEnd": 54.839294501566904,
        "alpSwing": 7.339294501566906,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 54.839294501566904,
        "alpEnd": 61.454049755765084,
        "alpSwing": 6.61475525419818,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 61.4,
        "alpEnd": 58.46287616906666,
        "alpSwing": -2.937123830933338,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "benambra",
    "districtName": "Benambra",
    "alpTpp2022": 36.74243345083262,
    "coalitionTpp2022": 63.25756654916738,
    "tppFormalVotes2022": 41135,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 45.97,
        "alpEnd": 42.29,
        "alpSwing": -3.6799999999999997,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 42.2915340547422,
        "alpEnd": 33.516416823450875,
        "alpSwing": -8.775117231291329,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 34.1,
        "alpEnd": 40.3256997455471,
        "alpSwing": 6.2256997455470975,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 40.3256997455471,
        "alpEnd": 41.08824807998841,
        "alpSwing": 0.7625483344413098,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "bendigo-east",
    "districtName": "Bendigo East",
    "alpTpp2022": 60.90915059858616,
    "coalitionTpp2022": 39.09084940141385,
    "tppFormalVotes2022": 45691,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 62.96000000000001,
        "alpEnd": 55.39000000000001,
        "alpSwing": -7.5699999999999985,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 55.39075703712337,
        "alpEnd": 53.816669385092155,
        "alpSwing": -1.5740876520312197,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 53.2,
        "alpEnd": 55.0477608237191,
        "alpSwing": 1.8477608237191023,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 55.0477608237191,
        "alpEnd": 62.11376078686091,
        "alpSwing": 7.065999963141801,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 62.1,
        "alpEnd": 60.90915059858616,
        "alpSwing": -1.1908494014138427,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bendigo-west",
    "districtName": "Bendigo West",
    "alpTpp2022": 64.34642547391897,
    "coalitionTpp2022": 35.65357452608103,
    "tppFormalVotes2022": 40355,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 65.94,
        "alpEnd": 60.56,
        "alpSwing": -5.3799999999999955,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 60.564215520162655,
        "alpEnd": 52.9333187939589,
        "alpSwing": -7.630896726203762,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 53.1,
        "alpEnd": 62.17570368038609,
        "alpSwing": 9.075703680386093,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 62.17570368038609,
        "alpEnd": 68.55039983700911,
        "alpSwing": 6.374696156623017,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 68.6,
        "alpEnd": 64.34642547391897,
        "alpSwing": -4.2535745260810245,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bentleigh",
    "districtName": "Bentleigh",
    "alpTpp2022": 58.040780141843975,
    "coalitionTpp2022": 41.959219858156025,
    "tppFormalVotes2022": 45120,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 54.74,
        "alpEnd": 56.32,
        "alpSwing": 1.5800000000000036,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 56.321702431195384,
        "alpEnd": 49.24723119520073,
        "alpSwing": -7.07447123599465,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 49.1,
        "alpEnd": 50.7817230938618,
        "alpSwing": 1.6817230938617977,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 50.7817230938618,
        "alpEnd": 61.91574833070952,
        "alpSwing": 11.134025236847723,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 61.4,
        "alpEnd": 58.040780141843975,
        "alpSwing": -3.359219858156024,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "berwick",
    "districtName": "Berwick",
    "alpTpp2022": 45.28599783471671,
    "coalitionTpp2022": 54.71400216528329,
    "tppFormalVotes2022": 44336,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 48.7,
        "alpEnd": 45.28599783471671,
        "alpSwing": -3.414002165283293,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "box-hill",
    "districtName": "Box Hill",
    "alpTpp2022": 57.22562900171341,
    "coalitionTpp2022": 42.77437099828659,
    "tppFormalVotes2022": 44356,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 48.91,
        "alpEnd": 44.78,
        "alpSwing": -4.129999999999995,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 44.77914002463776,
        "alpEnd": 36.196213916569114,
        "alpSwing": -8.58292610806865,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 40.6,
        "alpEnd": 44.3061318579991,
        "alpSwing": 3.7061318579990954,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 44.3061318579991,
        "alpEnd": 52.10294386065553,
        "alpSwing": 7.796812002656428,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 53.1,
        "alpEnd": 57.22562900171341,
        "alpSwing": 4.125629001713406,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "brighton",
    "districtName": "Brighton",
    "alpTpp2022": 45.78807627323196,
    "coalitionTpp2022": 54.21192372676804,
    "tppFormalVotes2022": 41430,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 42.59,
        "alpEnd": 39.07,
        "alpSwing": -3.5200000000000067,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 39.07399525749376,
        "alpEnd": 32.442949093036866,
        "alpSwing": -6.631046164456899,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 35.699999999999996,
        "alpEnd": 40.2288293489385,
        "alpSwing": 4.528829348938501,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 40.2288293489385,
        "alpEnd": 48.88413013751644,
        "alpSwing": 8.655300788577946,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49.5,
        "alpEnd": 45.78807627323196,
        "alpSwing": -3.711923726768042,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "broadmeadows",
    "districtName": "Broadmeadows",
    "alpTpp2022": 65.4513938222841,
    "coalitionTpp2022": 34.5486061777159,
    "tppFormalVotes2022": 35191,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 80.78,
        "alpEnd": 81.89,
        "alpSwing": 1.1099999999999999,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 81.89479228388966,
        "alpEnd": 70.97624471200781,
        "alpSwing": -10.918547571881854,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 70,
        "alpEnd": 77.8300762631077,
        "alpSwing": 7.830076263107699,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 77.8300762631077,
        "alpEnd": 80.28269206977608,
        "alpSwing": 2.452615806668379,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 75.2,
        "alpEnd": 65.4513938222841,
        "alpSwing": -9.7486061777159,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "brunswick",
    "districtName": "Brunswick",
    "alpTpp2022": 84.05570261249856,
    "coalitionTpp2022": 15.944297387501438,
    "tppFormalVotes2022": 43445,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 78.04,
        "alpEnd": 77.85,
        "alpSwing": -0.19000000000001238,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 77.85321597019858,
        "alpEnd": 75.1906930801734,
        "alpSwing": -2.662522890025165,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 75.1,
        "alpEnd": 79.3963872438487,
        "alpSwing": 4.296387243848699,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 79.3963872438487,
        "alpEnd": 84.38090468276914,
        "alpSwing": 4.984517438920443,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "bulleen",
    "districtName": "Bulleen",
    "alpTpp2022": 44.06487393391434,
    "coalitionTpp2022": 55.93512606608566,
    "tppFormalVotes2022": 42914,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 47.36,
        "alpEnd": 41.57,
        "alpSwing": -5.790000000000001,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 41.56891731208021,
        "alpEnd": 35.31916235650309,
        "alpSwing": -6.249754955577119,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 34.9,
        "alpEnd": 39.4460484963078,
        "alpSwing": 4.546048496307803,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 39.4460484963078,
        "alpEnd": 44.23200514138818,
        "alpSwing": 4.7859566450803745,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 44.5,
        "alpEnd": 44.06487393391434,
        "alpSwing": -0.4351260660856582,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "bundoora",
    "districtName": "Bundoora",
    "alpTpp2022": 62.735592381894634,
    "coalitionTpp2022": 37.264407618105366,
    "tppFormalVotes2022": 40430,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 67.57,
        "alpEnd": 65.12,
        "alpSwing": -2.4499999999999966,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 65.1241073394784,
        "alpEnd": 57.56223651413976,
        "alpSwing": -7.561870825338635,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 60.9,
        "alpEnd": 62.2264268165259,
        "alpSwing": 1.3264268165259052,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 62.2264268165259,
        "alpEnd": 67.42269213278763,
        "alpSwing": 5.196265316261728,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 66.2,
        "alpEnd": 62.735592381894634,
        "alpSwing": -3.464407618105369,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "carrum",
    "districtName": "Carrum",
    "alpTpp2022": 59.93634099086632,
    "coalitionTpp2022": 40.06365900913369,
    "tppFormalVotes2022": 43356,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 62.16,
        "alpEnd": 56.71000000000001,
        "alpSwing": -5.449999999999989,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 56.707629288274454,
        "alpEnd": 47.96277200497078,
        "alpSwing": -8.74485728330367,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 49.7,
        "alpEnd": 50.724159797083104,
        "alpSwing": 1.0241597970831018,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 50.724159797083104,
        "alpEnd": 61.94925279447623,
        "alpSwing": 11.225092997393126,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 62,
        "alpEnd": 59.93634099086632,
        "alpSwing": -2.06365900913368,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "caulfield",
    "districtName": "Caulfield",
    "alpTpp2022": 47.931568468402034,
    "coalitionTpp2022": 52.068431531597966,
    "tppFormalVotes2022": 40683,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 47.75,
        "alpEnd": 42.37,
        "alpSwing": -5.380000000000002,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 42.36672304704629,
        "alpEnd": 38.47111326998391,
        "alpSwing": -3.8956097770623863,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 40.2,
        "alpEnd": 45.1198465963567,
        "alpSwing": 4.919846596356697,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 45.1198465963567,
        "alpEnd": 49.73242392444911,
        "alpSwing": 4.61257732809241,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 50.2,
        "alpEnd": 47.931568468402034,
        "alpSwing": -2.268431531597969,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "clarinda",
    "districtName": "Clarinda",
    "alpTpp2022": 60.36804088251192,
    "coalitionTpp2022": 39.63195911748809,
    "tppFormalVotes2022": 40702,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 62.4,
        "alpEnd": 65.8481610140277,
        "alpSwing": 3.4481610140276953,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 65.8481610140277,
        "alpEnd": 67.42465455336742,
        "alpSwing": 1.5764935393397295,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 64.9,
        "alpEnd": 60.36804088251192,
        "alpSwing": -4.5319591174880856,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "cranbourne",
    "districtName": "Cranbourne",
    "alpTpp2022": 58.99931693989071,
    "coalitionTpp2022": 41.00068306010929,
    "tppFormalVotes2022": 40992,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 60.79,
        "alpEnd": 61.29,
        "alpSwing": 0.5000000000000004,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 61.28626530269998,
        "alpEnd": 51.84946544482627,
        "alpSwing": -9.436799857873712,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 51.1,
        "alpEnd": 52.3365886554937,
        "alpSwing": 1.2365886554936978,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 52.3365886554937,
        "alpEnd": 60.98183660742127,
        "alpSwing": 8.645247951927571,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 59.3,
        "alpEnd": 58.99931693989071,
        "alpSwing": -0.3006830601092858,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "croydon",
    "districtName": "Croydon",
    "alpTpp2022": 48.62727053616425,
    "coalitionTpp2022": 51.37272946383575,
    "tppFormalVotes2022": 45639,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 37.8,
        "alpEnd": 40.7081076711664,
        "alpSwing": 2.908107671166399,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 40.7081076711664,
        "alpEnd": 47.885868701319346,
        "alpSwing": 7.177761030152946,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49,
        "alpEnd": 48.62727053616425,
        "alpSwing": -0.37272946383575345,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "dandenong",
    "districtName": "Dandenong",
    "alpTpp2022": 69.10558849501703,
    "coalitionTpp2022": 30.894411504982973,
    "tppFormalVotes2022": 39635,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 70.31,
        "alpEnd": 68.67,
        "alpSwing": -1.6400000000000081,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 68.66513902664249,
        "alpEnd": 63.86568829675717,
        "alpSwing": -4.799450729885324,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 64,
        "alpEnd": 62.8773848369933,
        "alpSwing": -1.1226151630067016,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 62.8773848369933,
        "alpEnd": 73.92775160082155,
        "alpSwing": 11.050366763828256,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 73.1,
        "alpEnd": 69.10558849501703,
        "alpSwing": -3.9944115049829634,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "eildon",
    "districtName": "Eildon",
    "alpTpp2022": 42.92379471228615,
    "coalitionTpp2022": 57.07620528771385,
    "tppFormalVotes2022": 42438,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 42.3,
        "alpEnd": 46.247809087232,
        "alpSwing": 3.9478090872320015,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 46.247809087232,
        "alpEnd": 47.56368521676226,
        "alpSwing": 1.315876129530258,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49,
        "alpEnd": 42.92379471228615,
        "alpSwing": -6.076205287713847,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "eltham",
    "districtName": "Eltham",
    "alpTpp2022": 59.004652860140496,
    "coalitionTpp2022": 40.9953471398595,
    "tppFormalVotes2022": 43844,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 54.78999999999999,
        "alpEnd": 56.48,
        "alpSwing": 1.6900000000000026,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 56.48470991711918,
        "alpEnd": 50.816509143783904,
        "alpSwing": -5.668200773335275,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 50.8,
        "alpEnd": 52.694462346933705,
        "alpSwing": 1.8944623469337007,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 52.694462346933705,
        "alpEnd": 59.073761540752514,
        "alpSwing": 6.37929919381881,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 58.8,
        "alpEnd": 59.004652860140496,
        "alpSwing": 0.20465286014049866,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "essendon",
    "districtName": "Essendon",
    "alpTpp2022": 62.45013972818688,
    "coalitionTpp2022": 37.549860271813124,
    "tppFormalVotes2022": 41867,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 65.92,
        "alpEnd": 61.7,
        "alpSwing": -4.2200000000000015,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 61.70044428214959,
        "alpEnd": 52.4201327810248,
        "alpSwing": -9.280311501124794,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 54.300000000000004,
        "alpEnd": 58.668300028073396,
        "alpSwing": 4.36830002807339,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 58.668300028073396,
        "alpEnd": 65.86371527777779,
        "alpSwing": 7.195415249704384,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 65.8,
        "alpEnd": 62.45013972818688,
        "alpSwing": -3.349860271813114,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "eureka",
    "districtName": "Eureka",
    "alpTpp2022": 57.17285123875616,
    "coalitionTpp2022": 42.82714876124384,
    "tppFormalVotes2022": 45247,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 59.599999999999994,
        "alpEnd": 57.17285123875616,
        "alpSwing": -2.427148761243835,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "euroa",
    "districtName": "Euroa",
    "alpTpp2022": 40.06912551489039,
    "coalitionTpp2022": 59.93087448510961,
    "tppFormalVotes2022": 42242,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 36.4,
        "alpEnd": 35.5341083570959,
        "alpSwing": -0.8658916429040986,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 35.5341083570959,
        "alpEnd": 34.56083248200328,
        "alpSwing": -0.9732758750926218,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 34.2,
        "alpEnd": 40.06912551489039,
        "alpSwing": 5.869125514890385,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "evelyn",
    "districtName": "Evelyn",
    "alpTpp2022": 44.78510750349186,
    "coalitionTpp2022": 55.21489249650814,
    "tppFormalVotes2022": 43673,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 50.33,
        "alpEnd": 47.22,
        "alpSwing": -3.109999999999996,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 47.22026120720085,
        "alpEnd": 36.519062147824414,
        "alpSwing": -10.701199059376432,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 37.4,
        "alpEnd": 40.4073477995449,
        "alpSwing": 3.0073477995449016,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 40.4073477995449,
        "alpEnd": 47.35060504291273,
        "alpSwing": 6.943257243367834,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 48.2,
        "alpEnd": 44.78510750349186,
        "alpSwing": -3.414892496508145,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "footscray",
    "districtName": "Footscray",
    "alpTpp2022": 75.66435299950422,
    "coalitionTpp2022": 24.335647000495786,
    "tppFormalVotes2022": 40340,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 74.9,
        "alpEnd": 74.67,
        "alpSwing": -0.23000000000000798,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 74.66853646098929,
        "alpEnd": 66.23316031958943,
        "alpSwing": -8.435376141399853,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 65.9,
        "alpEnd": 64.4891553245684,
        "alpSwing": -1.4108446754315995,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 64.4891553245684,
        "alpEnd": 78.11146473952476,
        "alpSwing": 13.622309414956357,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 77.6,
        "alpEnd": 75.66435299950422,
        "alpSwing": -1.935647000495777,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "frankston",
    "districtName": "Frankston",
    "alpTpp2022": 58.65902205753486,
    "coalitionTpp2022": 41.34097794246514,
    "tppFormalVotes2022": 39941,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 55.77000000000001,
        "alpEnd": 53.22,
        "alpSwing": -2.550000000000008,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 53.21511277479936,
        "alpEnd": 47.93053636477829,
        "alpSwing": -5.284576410021064,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 49.6,
        "alpEnd": 50.480082299822804,
        "alpSwing": 0.8800822998228042,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 50.480082299822804,
        "alpEnd": 59.743861652663355,
        "alpSwing": 9.263779352840551,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 60.199999999999996,
        "alpEnd": 58.65902205753486,
        "alpSwing": -1.5409779424651333,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "geelong",
    "districtName": "Geelong",
    "alpTpp2022": 64.70890487467048,
    "coalitionTpp2022": 35.29109512532952,
    "tppFormalVotes2022": 44762,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 58.099999999999994,
        "alpEnd": 58.32999999999999,
        "alpSwing": 0.22999999999999687,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 58.32804293876609,
        "alpEnd": 52.14043475843665,
        "alpSwing": -6.18760818032944,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 54,
        "alpEnd": 56.032790957645,
        "alpSwing": 2.032790957644992,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 56.032790957645,
        "alpEnd": 60.1389292283861,
        "alpSwing": 4.1061382707411,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 60.3,
        "alpEnd": 64.70890487467048,
        "alpSwing": 4.408904874670483,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "gippsland-east",
    "districtName": "Gippsland East",
    "alpTpp2022": 26.077188667644137,
    "coalitionTpp2022": 73.92281133235586,
    "tppFormalVotes2022": 42286,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 39.82,
        "alpEnd": 36.46,
        "alpSwing": -3.3599999999999963,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 36.46259286989576,
        "alpEnd": 26.88569000318708,
        "alpSwing": -9.576902866708675,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 26.900000000000002,
        "alpEnd": 32.0878143234686,
        "alpSwing": 5.187814323468598,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 32.0878143234686,
        "alpEnd": 32.40838751953223,
        "alpSwing": 0.32057319606363377,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 32.4,
        "alpEnd": 26.077188667644137,
        "alpSwing": -6.322811332355862,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "gippsland-south",
    "districtName": "Gippsland South",
    "alpTpp2022": 34.7502832326284,
    "coalitionTpp2022": 65.2497167673716,
    "tppFormalVotes2022": 42368,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 39.15,
        "alpEnd": 34.19,
        "alpSwing": -4.959999999999997,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 34.187546886721684,
        "alpEnd": 27.40717610991257,
        "alpSwing": -6.7803707768091135,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 27.400000000000002,
        "alpEnd": 34.3344881537774,
        "alpSwing": 6.934488153777396,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 34.3344881537774,
        "alpEnd": 34.67363914704528,
        "alpSwing": 0.33915099326787823,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 35.8,
        "alpEnd": 34.7502832326284,
        "alpSwing": -1.0497167673715992,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "glen-waverley",
    "districtName": "Glen Waverley",
    "alpTpp2022": 53.30333355721226,
    "coalitionTpp2022": 46.696666442787745,
    "tppFormalVotes2022": 44667,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 49.1,
        "alpEnd": 53.30333355721226,
        "alpSwing": 4.203333557212261,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "greenvale",
    "districtName": "Greenvale",
    "alpTpp2022": 56.91938377123562,
    "coalitionTpp2022": 43.08061622876438,
    "tppFormalVotes2022": 37908,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 72,
        "alpEnd": 56.91938377123562,
        "alpSwing": -15.080616228764377,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "hastings",
    "districtName": "Hastings",
    "alpTpp2022": 51.353317811408616,
    "coalitionTpp2022": 48.646682188591384,
    "tppFormalVotes2022": 41232,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 50.85000000000001,
        "alpEnd": 49.01,
        "alpSwing": -1.8400000000000083,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 49.00942223204664,
        "alpEnd": 39.215099608547135,
        "alpSwing": -9.794322623499502,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 40.400000000000006,
        "alpEnd": 42.3500347780203,
        "alpSwing": 1.9500347780202987,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 42.3500347780203,
        "alpEnd": 48.935589519650655,
        "alpSwing": 6.585554741630356,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 50.01,
        "alpEnd": 51.353317811408616,
        "alpSwing": 1.3433178114086175,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "hawthorn",
    "districtName": "Hawthorn",
    "alpTpp2022": 48.25772963213721,
    "coalitionTpp2022": 51.74227036786279,
    "tppFormalVotes2022": 44310,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 44.12,
        "alpEnd": 37.74,
        "alpSwing": -6.379999999999997,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 37.74044893711907,
        "alpEnd": 33.261945417185196,
        "alpSwing": -4.478503519933874,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 33.4,
        "alpEnd": 41.408368334308,
        "alpSwing": 8.008368334307997,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 41.408368334308,
        "alpEnd": 50.420317913185244,
        "alpSwing": 9.011949578877243,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 50.6,
        "alpEnd": 48.25772963213721,
        "alpSwing": -2.3422703678627883,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "ivanhoe",
    "districtName": "Ivanhoe",
    "alpTpp2022": 62.750314047144016,
    "coalitionTpp2022": 37.249685952855984,
    "tppFormalVotes2022": 40599,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 62.49,
        "alpEnd": 60.45,
        "alpSwing": -2.0399999999999974,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 60.44549647972809,
        "alpEnd": 51.673512190859036,
        "alpSwing": -8.77198428886905,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 51.800000000000004,
        "alpEnd": 53.4094956999644,
        "alpSwing": 1.6094956999644028,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 53.4094956999644,
        "alpEnd": 62.36936380481779,
        "alpSwing": 8.959868104853385,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 62.3,
        "alpEnd": 62.750314047144016,
        "alpSwing": 0.450314047144019,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "kalkallo",
    "districtName": "Kalkallo",
    "alpTpp2022": 66.43081369275998,
    "coalitionTpp2022": 33.569186307240024,
    "tppFormalVotes2022": 40138,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 70.9,
        "alpEnd": 66.43081369275998,
        "alpSwing": -4.469186307240022,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "kew",
    "districtName": "Kew",
    "alpTpp2022": 46.024499908240045,
    "coalitionTpp2022": 53.975500091759955,
    "tppFormalVotes2022": 43592,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 44.02,
        "alpEnd": 40.44,
        "alpSwing": -3.5800000000000054,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 40.44083309984123,
        "alpEnd": 34.808901790033865,
        "alpSwing": -5.6319313098073644,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 34.300000000000004,
        "alpEnd": 39.3564921718389,
        "alpSwing": 5.0564921718389,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 39.3564921718389,
        "alpEnd": 45.22304497020047,
        "alpSwing": 5.866552798361568,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 45.3,
        "alpEnd": 46.024499908240045,
        "alpSwing": 0.7244999082400483,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "kororoit",
    "districtName": "Kororoit",
    "alpTpp2022": 64.24695556500212,
    "coalitionTpp2022": 35.753044434997875,
    "tppFormalVotes2022": 39991,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 77.05,
        "alpEnd": 75.56,
        "alpSwing": -1.4899999999999913,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 75.55706437874206,
        "alpEnd": 68.58032308727844,
        "alpSwing": -6.976741291463617,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 67.5,
        "alpEnd": 69.97960365623351,
        "alpSwing": 2.4796036562334978,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 69.97960365623351,
        "alpEnd": 75.64570365600629,
        "alpSwing": 5.666099999772789,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 75.3,
        "alpEnd": 64.24695556500212,
        "alpSwing": -11.053044434997872,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "lara",
    "districtName": "Lara",
    "alpTpp2022": 66.15310908265671,
    "coalitionTpp2022": 33.84689091734329,
    "tppFormalVotes2022": 39658,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 72.34,
        "alpEnd": 67.93,
        "alpSwing": -4.410000000000003,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 67.9275212006589,
        "alpEnd": 65.39575040066174,
        "alpSwing": -2.5317707999971684,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 63.800000000000004,
        "alpEnd": 67.10979042852671,
        "alpSwing": 3.3097904285267044,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 67.10979042852671,
        "alpEnd": 69.13847860059484,
        "alpSwing": 2.0286881720681382,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 69.1,
        "alpEnd": 66.15310908265671,
        "alpSwing": -2.946890917343282,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "laverton",
    "districtName": "Laverton",
    "alpTpp2022": 68.01397473797365,
    "coalitionTpp2022": 31.986025262026335,
    "tppFormalVotes2022": 37210,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 73.4,
        "alpEnd": 68.01397473797365,
        "alpSwing": -5.386025262026351,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "lowan",
    "districtName": "Lowan",
    "alpTpp2022": 28.392522932600105,
    "coalitionTpp2022": 71.6074770673999,
    "tppFormalVotes2022": 43279,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 32.92,
        "alpEnd": 27.92,
        "alpSwing": -4.999999999999999,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 27.917633244551364,
        "alpEnd": 27.91544567413013,
        "alpSwing": -0.0021875704212359626,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 28.1,
        "alpEnd": 28.7360156009443,
        "alpSwing": 0.6360156009442952,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 28.7360156009443,
        "alpEnd": 26.5184836108493,
        "alpSwing": -2.2175319900949955,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 28.9,
        "alpEnd": 28.392522932600105,
        "alpSwing": -0.5074770673998934,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "macedon",
    "districtName": "Macedon",
    "alpTpp2022": 59.53978215393494,
    "coalitionTpp2022": 40.46021784606506,
    "tppFormalVotes2022": 41589,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 59.25,
        "alpEnd": 58.17,
        "alpSwing": -1.0800000000000032,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 58.16533552479519,
        "alpEnd": 51.259622113365985,
        "alpSwing": -6.905713411429204,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 52.300000000000004,
        "alpEnd": 53.7926491898301,
        "alpSwing": 1.4926491898300975,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 53.7926491898301,
        "alpEnd": 63.178854099258295,
        "alpSwing": 9.386204909428198,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 63.4,
        "alpEnd": 59.53978215393494,
        "alpSwing": -3.860217846065062,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "malvern",
    "districtName": "Malvern",
    "alpTpp2022": 41.717791411042946,
    "coalitionTpp2022": 58.282208588957054,
    "tppFormalVotes2022": 40750,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 39.82,
        "alpEnd": 38.68,
        "alpSwing": -1.1400000000000021,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 38.6752611691487,
        "alpEnd": 29.56288343558282,
        "alpSwing": -9.112377733565879,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 29.5,
        "alpEnd": 33.7499654342837,
        "alpSwing": 4.249965434283704,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 33.7499654342837,
        "alpEnd": 43.89606188846061,
        "alpSwing": 10.146096454176906,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 44,
        "alpEnd": 41.717791411042946,
        "alpSwing": -2.2822085889570545,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "melbourne",
    "districtName": "Melbourne",
    "alpTpp2022": 75.0135233660246,
    "coalitionTpp2022": 24.9864766339754,
    "tppFormalVotes2022": 42519,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 72.17,
        "alpEnd": 71.43,
        "alpSwing": -0.7399999999999962,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 71.43037137367311,
        "alpEnd": 64.41374058258764,
        "alpSwing": -7.016630791085465,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 63.5,
        "alpEnd": 70.4621621621622,
        "alpSwing": 6.962162162162199,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 70.4621621621622,
        "alpEnd": 75.25457997386394,
        "alpSwing": 4.7924178117017435,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "melton",
    "districtName": "Melton",
    "alpTpp2022": 54.59475265158563,
    "coalitionTpp2022": 45.40524734841436,
    "tppFormalVotes2022": 37619,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 65.32,
        "alpEnd": 63.54,
        "alpSwing": -1.7799999999999927,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 63.53889774942406,
        "alpEnd": 62.78020922288642,
        "alpSwing": -0.7586885265376431,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 63.6,
        "alpEnd": 61.2167795726941,
        "alpSwing": -2.383220427305899,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 61.2167795726941,
        "alpEnd": 54.286053976934966,
        "alpSwing": -6.930725595759135,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 55.00000000000001,
        "alpEnd": 54.59475265158563,
        "alpSwing": -0.4052473484143775,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "mildura",
    "districtName": "Mildura",
    "alpTpp2022": 35.88358678552701,
    "coalitionTpp2022": 64.11641321447298,
    "tppFormalVotes2022": 38140,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 43.29,
        "alpEnd": 29.31,
        "alpSwing": -13.980000000000004,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 29.305525018060745,
        "alpEnd": 37.201648622047244,
        "alpSwing": 7.896123603986499,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 35.5,
        "alpEnd": 29.780985838182,
        "alpSwing": -5.719014161817998,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 29.780985838182,
        "alpEnd": 44.38680893380278,
        "alpSwing": 14.60582309562078,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "mill-park",
    "districtName": "Mill Park",
    "alpTpp2022": 61.43423137876387,
    "coalitionTpp2022": 38.56576862123614,
    "tppFormalVotes2022": 37860,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 76.78,
        "alpEnd": 70.79,
        "alpSwing": -5.989999999999995,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 70.78789292587625,
        "alpEnd": 69.45031712473573,
        "alpSwing": -1.3375758011405225,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 66.9,
        "alpEnd": 69.8539952216618,
        "alpSwing": 2.953995221661798,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 69.8539952216618,
        "alpEnd": 74.89495266541792,
        "alpSwing": 5.0409574437561115,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 74.9,
        "alpEnd": 61.43423137876387,
        "alpSwing": -13.465768621236137,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "monbulk",
    "districtName": "Monbulk",
    "alpTpp2022": 57.55436993085629,
    "coalitionTpp2022": 42.44563006914372,
    "tppFormalVotes2022": 41797,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 58.26,
        "alpEnd": 56.68,
        "alpSwing": -1.5800000000000036,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 56.67962889249518,
        "alpEnd": 51.877493546115936,
        "alpSwing": -4.802135346379243,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 48.9,
        "alpEnd": 54.9776286353468,
        "alpSwing": 6.077628635346799,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 54.9776286353468,
        "alpEnd": 58.61324628830157,
        "alpSwing": 3.63561765295477,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 57.10000000000001,
        "alpEnd": 57.55436993085629,
        "alpSwing": 0.45436993085628075,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "mordialloc",
    "districtName": "Mordialloc",
    "alpTpp2022": 58.19469347919834,
    "coalitionTpp2022": 41.80530652080166,
    "tppFormalVotes2022": 44059,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 54.53,
        "alpEnd": 53.54,
        "alpSwing": -0.990000000000002,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 53.54495558196118,
        "alpEnd": 47.93078116072157,
        "alpSwing": -5.61417442123961,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 48.5,
        "alpEnd": 52.0962611461647,
        "alpSwing": 3.596261146164703,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 52.0962611461647,
        "alpEnd": 62.90221766632498,
        "alpSwing": 10.805956520160276,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 63.4,
        "alpEnd": 58.19469347919834,
        "alpSwing": -5.205306520801656,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "mornington",
    "districtName": "Mornington",
    "alpTpp2022": 41.719366649232086,
    "coalitionTpp2022": 58.28063335076792,
    "tppFormalVotes2022": 42062,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 48.18,
        "alpEnd": 38.15,
        "alpSwing": -10.03,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 38.14947260870872,
        "alpEnd": 33.97294312534511,
        "alpSwing": -4.1765294833636055,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 33.800000000000004,
        "alpEnd": 37.3929566759564,
        "alpSwing": 3.5929566759563993,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 37.3929566759564,
        "alpEnd": 45.005191606500375,
        "alpSwing": 7.612234930543971,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 45,
        "alpEnd": 41.719366649232086,
        "alpSwing": -3.280633350767914,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "morwell",
    "districtName": "Morwell",
    "alpTpp2022": 45.58378215945078,
    "coalitionTpp2022": 54.41621784054922,
    "tppFormalVotes2022": 43261,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 54.86,
        "alpEnd": 47.88,
        "alpSwing": -6.979999999999997,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 47.884627074341985,
        "alpEnd": 33.73957665169981,
        "alpSwing": -14.145050422642175,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 36.7,
        "alpEnd": 48.200847246449,
        "alpSwing": 11.500847246449004,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 48.200847246449,
        "alpEnd": 52.406457077375315,
        "alpSwing": 4.20560983092631,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 54,
        "alpEnd": 45.58378215945078,
        "alpSwing": -8.416217840549223,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "mulgrave",
    "districtName": "Mulgrave",
    "alpTpp2022": 60.19860088558179,
    "coalitionTpp2022": 39.80139911441821,
    "tppFormalVotes2022": 38167,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 66.22,
        "alpEnd": 65.77,
        "alpSwing": -0.45000000000000595,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 65.76722432092103,
        "alpEnd": 58.4797052825472,
        "alpSwing": -7.287519038373825,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 52.400000000000006,
        "alpEnd": 54.479006834984,
        "alpSwing": 2.0790068349839985,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 54.479006834984,
        "alpEnd": 62.70545076403131,
        "alpSwing": 8.226443929047312,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 65.8,
        "alpEnd": 60.19860088558179,
        "alpSwing": -5.601399114418207,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "murray-plains",
    "districtName": "Murray Plains",
    "alpTpp2022": 27.112457477714596,
    "coalitionTpp2022": 72.8875425222854,
    "tppFormalVotes2022": 40273,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 19.8,
        "alpEnd": 27.6317425580065,
        "alpSwing": 7.831742558006499,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 27.6317425580065,
        "alpEnd": 26.045712578428443,
        "alpSwing": -1.5860299795780575,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 26,
        "alpEnd": 27.112457477714596,
        "alpSwing": 1.112457477714596,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "narre-warren-north",
    "districtName": "Narre Warren North",
    "alpTpp2022": 59.16341381138258,
    "coalitionTpp2022": 40.83658618861742,
    "tppFormalVotes2022": 41502,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 59.699999999999996,
        "alpEnd": 59.23,
        "alpSwing": -0.47000000000000375,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 59.233889139251914,
        "alpEnd": 52.96944342369336,
        "alpSwing": -6.264445715558553,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 54.800000000000004,
        "alpEnd": 54.563454900596696,
        "alpSwing": -0.23654509940330692,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 54.563454900596696,
        "alpEnd": 59.75645500812705,
        "alpSwing": 5.193000107530354,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 60.4,
        "alpEnd": 59.16341381138258,
        "alpSwing": -1.2365861886174159,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "narre-warren-south",
    "districtName": "Narre Warren South",
    "alpTpp2022": 58.49576320642406,
    "coalitionTpp2022": 41.50423679357595,
    "tppFormalVotes2022": 42839,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 62.6,
        "alpEnd": 60.94,
        "alpSwing": -1.660000000000006,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 60.94212082805238,
        "alpEnd": 56.73526152241466,
        "alpSwing": -4.206859305637723,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 57.4,
        "alpEnd": 55.49077253749039,
        "alpSwing": -1.9092274625095995,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 55.49077253749039,
        "alpEnd": 56.895143858974976,
        "alpSwing": 1.4043713214845766,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 60.4,
        "alpEnd": 58.49576320642406,
        "alpSwing": -1.9042367935759401,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "nepean",
    "districtName": "Nepean",
    "alpTpp2022": 43.317893292159894,
    "coalitionTpp2022": 56.682106707840106,
    "tppFormalVotes2022": 40803,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 49.83,
        "alpEnd": 40.62,
        "alpSwing": -9.21,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 40.62335734825763,
        "alpEnd": 35.69161521149518,
        "alpSwing": -4.931742136762446,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 36.3,
        "alpEnd": 42.3688353903195,
        "alpSwing": 6.068835390319499,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 42.3688353903195,
        "alpEnd": 50.90754194571314,
        "alpSwing": 8.538706555393643,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 50.7,
        "alpEnd": 43.317893292159894,
        "alpSwing": -7.382106707840109,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "niddrie",
    "districtName": "Niddrie",
    "alpTpp2022": 56.69475877089153,
    "coalitionTpp2022": 43.30524122910847,
    "tppFormalVotes2022": 42242,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 66.6,
        "alpEnd": 61.22,
        "alpSwing": -5.3799999999999955,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 61.21701805327611,
        "alpEnd": 56.948288877705075,
        "alpSwing": -4.268729175571028,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 54.50000000000001,
        "alpEnd": 57.710833754690405,
        "alpSwing": 3.210833754690401,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 57.710833754690405,
        "alpEnd": 62.58891581333542,
        "alpSwing": 4.878082058645017,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 62.5,
        "alpEnd": 56.69475877089153,
        "alpSwing": -5.805241229108468,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "northcote",
    "districtName": "Northcote",
    "alpTpp2022": 81.70348482716571,
    "coalitionTpp2022": 18.296515172834297,
    "tppFormalVotes2022": 42642,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 78.32,
        "alpEnd": 80.29,
        "alpSwing": 1.9700000000000162,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 80.293702513589,
        "alpEnd": 75.88947338650375,
        "alpSwing": -4.404229127085236,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 75.5,
        "alpEnd": 79.82043168428909,
        "alpSwing": 4.320431684289094,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 79.82043168428909,
        "alpEnd": 83.2322805038541,
        "alpSwing": 3.411848819565011,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "oakleigh",
    "districtName": "Oakleigh",
    "alpTpp2022": 63.48439990890458,
    "coalitionTpp2022": 36.51560009109542,
    "tppFormalVotes2022": 43910,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 65.21,
        "alpEnd": 62.36999999999999,
        "alpSwing": -2.839999999999998,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 62.37218143681174,
        "alpEnd": 54.70960358584735,
        "alpSwing": -7.662577850964403,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 55.1,
        "alpEnd": 58.1818181818182,
        "alpSwing": 3.0818181818181967,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 58.1818181818182,
        "alpEnd": 65.78440942685818,
        "alpSwing": 7.60259124503998,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 66,
        "alpEnd": 63.48439990890458,
        "alpSwing": -2.515600091095422,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "ovens-valley",
    "districtName": "Ovens Valley",
    "alpTpp2022": 32.03391506402333,
    "coalitionTpp2022": 67.96608493597667,
    "tppFormalVotes2022": 40454,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 30.8,
        "alpEnd": 33.4311408156057,
        "alpSwing": 2.631140815605698,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 33.4311408156057,
        "alpEnd": 37.37508327781479,
        "alpSwing": 3.9439424622090935,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 37.9,
        "alpEnd": 32.03391506402333,
        "alpSwing": -5.866084935976666,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "pakenham",
    "districtName": "Pakenham",
    "alpTpp2022": 50.39493657858852,
    "coalitionTpp2022": 49.60506342141148,
    "tppFormalVotes2022": 38867,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 52.2,
        "alpEnd": 50.39493657858852,
        "alpSwing": -1.8050634214114822,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "pascoe-vale",
    "districtName": "Pascoe Vale",
    "alpTpp2022": 72.246914806446,
    "coalitionTpp2022": 27.753085193553993,
    "tppFormalVotes2022": 40273,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 74.2,
        "alpEnd": 72.78,
        "alpSwing": -1.419999999999999,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 72.77947464874771,
        "alpEnd": 67.80348471865182,
        "alpSwing": -4.975989930095892,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 68.5,
        "alpEnd": 66.7718298392021,
        "alpSwing": -1.7281701607979039,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 66.7718298392021,
        "alpEnd": 68.31988609397247,
        "alpSwing": 1.5480562547703691,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 72.3,
        "alpEnd": 72.246914806446,
        "alpSwing": -0.0530851935539971,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "point-cook",
    "districtName": "Point Cook",
    "alpTpp2022": 58.33908795621371,
    "coalitionTpp2022": 41.66091204378628,
    "tppFormalVotes2022": 39099,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2018–22",
        "alpStart": 62.8,
        "alpEnd": 58.33908795621371,
        "alpSwing": -4.460912043786287,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "polwarth",
    "districtName": "Polwarth",
    "alpTpp2022": 48.21312116864484,
    "coalitionTpp2022": 51.78687883135515,
    "tppFormalVotes2022": 46002,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 40.47,
        "alpEnd": 39.31,
        "alpSwing": -1.16,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 39.312831157480744,
        "alpEnd": 36.71448619990644,
        "alpSwing": -2.5983449575743056,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 36.199999999999996,
        "alpEnd": 39.3592503482335,
        "alpSwing": 3.1592503482335,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 39.3592503482335,
        "alpEnd": 44.597239773036996,
        "alpSwing": 5.237989424803496,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 48,
        "alpEnd": 48.21312116864484,
        "alpSwing": 0.21312116864483954,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "prahran",
    "districtName": "Prahran",
    "alpTpp2022": 61.070764212725834,
    "coalitionTpp2022": 38.929235787274166,
    "tppFormalVotes2022": 39243,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 54.42,
        "alpEnd": 53.55,
        "alpSwing": -0.8700000000000041,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 53.55264416180548,
        "alpEnd": 45.72181430601611,
        "alpSwing": -7.8308298557893785,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 45.300000000000004,
        "alpEnd": 49.966339033257,
        "alpSwing": 4.666339033257,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 49.966339033257,
        "alpEnd": 57.55034387214884,
        "alpSwing": 7.5840048388918335,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "preston",
    "districtName": "Preston",
    "alpTpp2022": 69.67157588378453,
    "coalitionTpp2022": 30.32842411621547,
    "tppFormalVotes2022": 39857,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 75.75,
        "alpEnd": 75.3,
        "alpSwing": -0.44999999999999485,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 75.3031150904682,
        "alpEnd": 70.3841612932522,
        "alpSwing": -4.9189537972159965,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 70.19999999999999,
        "alpEnd": 74.65279683811819,
        "alpSwing": 4.4527968381182,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 74.65279683811819,
        "alpEnd": 78.50372195148074,
        "alpSwing": 3.8509251133625466,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "richmond",
    "districtName": "Richmond",
    "alpTpp2022": 74.12599733205809,
    "coalitionTpp2022": 25.87400266794191,
    "tppFormalVotes2022": 39731,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 75.55,
        "alpEnd": 75.17,
        "alpSwing": -0.37999999999999146,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 75.16870782304423,
        "alpEnd": 70.24851144718085,
        "alpSwing": -4.920196375863394,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 70.39999999999999,
        "alpEnd": 73.0711685202733,
        "alpSwing": 2.6711685202733038,
        "comparison": "Redistribution-adjusted"
      }
    ]
  },
  {
    "districtId": "ringwood",
    "districtName": "Ringwood",
    "alpTpp2022": 57.53065372762441,
    "coalitionTpp2022": 42.46934627237558,
    "tppFormalVotes2022": 45753,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 43.7,
        "alpEnd": 44.9279769968758,
        "alpSwing": 1.2279769968758014,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 44.9279769968758,
        "alpEnd": 52.81937099916504,
        "alpSwing": 7.891394002289237,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 53.2,
        "alpEnd": 57.53065372762441,
        "alpSwing": 4.330653727624409,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "ripon",
    "districtName": "Ripon",
    "alpTpp2022": 52.99355234878723,
    "coalitionTpp2022": 47.006447651212774,
    "tppFormalVotes2022": 42341,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 57.43000000000001,
        "alpEnd": 54.35,
        "alpSwing": -3.080000000000005,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 54.347431475766925,
        "alpEnd": 52.70735617170338,
        "alpSwing": -1.6400753040635485,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 48.4,
        "alpEnd": 49.2498190079137,
        "alpSwing": 0.8498190079136991,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 49.2498190079137,
        "alpEnd": 49.98127574584946,
        "alpSwing": 0.7314567379357595,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 52.800000000000004,
        "alpEnd": 52.99355234878723,
        "alpSwing": 0.19355234878722882,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "rowville",
    "districtName": "Rowville",
    "alpTpp2022": 46.33493970347483,
    "coalitionTpp2022": 53.66506029652517,
    "tppFormalVotes2022": 43369,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 36.9,
        "alpEnd": 41.5896965176984,
        "alpSwing": 4.689696517698399,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 41.5896965176984,
        "alpEnd": 44.31285751243209,
        "alpSwing": 2.723160994733692,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 44.5,
        "alpEnd": 46.33493970347483,
        "alpSwing": 1.8349397034748307,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "sandringham",
    "districtName": "Sandringham",
    "alpTpp2022": 44.850424719931056,
    "coalitionTpp2022": 55.149575280068944,
    "tppFormalVotes2022": 40615,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 46.97,
        "alpEnd": 41.32,
        "alpSwing": -5.6499999999999995,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 41.323944516951464,
        "alpEnd": 34.06958618864151,
        "alpSwing": -7.254358328309957,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 34.4,
        "alpEnd": 42.6660949267012,
        "alpSwing": 8.2660949267012,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 42.6660949267012,
        "alpEnd": 49.35326169985232,
        "alpSwing": 6.687166773151121,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 49.6,
        "alpEnd": 44.850424719931056,
        "alpSwing": -4.749575280068946,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "shepparton",
    "districtName": "Shepparton",
    "alpTpp2022": 25.65797438318685,
    "coalitionTpp2022": 74.34202561681316,
    "tppFormalVotes2022": 41301,
    "tppMethod2022": "2PP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 34.87,
        "alpEnd": 25.35,
        "alpSwing": -9.519999999999996,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 25.34842937574993,
        "alpEnd": 24.030775678831244,
        "alpSwing": -1.3176536969186885,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 24.099999999999998,
        "alpEnd": 36.7203368838246,
        "alpSwing": 12.620336883824601,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 36.7203368838246,
        "alpEnd": 38.28045531605716,
        "alpSwing": 1.5601184322325545,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "south-barwon",
    "districtName": "South Barwon",
    "alpTpp2022": 59.79992917847026,
    "coalitionTpp2022": 40.20007082152974,
    "tppFormalVotes2022": 45184,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 55.010000000000005,
        "alpEnd": 52.28,
        "alpSwing": -2.729999999999999,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 52.27551646553488,
        "alpEnd": 46.06201444421662,
        "alpSwing": -6.213502021318257,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 45.1,
        "alpEnd": 47.1417365298818,
        "alpSwing": 2.041736529881799,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 47.1417365298818,
        "alpEnd": 54.597177969959034,
        "alpSwing": 7.455441440077232,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 53,
        "alpEnd": 59.79992917847026,
        "alpSwing": 6.799929178470258,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "south-west-coast",
    "districtName": "South-West Coast",
    "alpTpp2022": 41.95094074204326,
    "coalitionTpp2022": 58.04905925795675,
    "tppFormalVotes2022": 45496,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 49.26,
        "alpEnd": 45.99,
        "alpSwing": -3.269999999999995,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 45.994594594594595,
        "alpEnd": 38.09791209352188,
        "alpSwing": -7.896682501072721,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 38.1,
        "alpEnd": 39.027434472969304,
        "alpSwing": 0.9274344729693018,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 39.027434472969304,
        "alpEnd": 47.6853768415926,
        "alpSwing": 8.657942368623296,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 46.8,
        "alpEnd": 41.95094074204326,
        "alpSwing": -4.849059257956739,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "st-albans",
    "districtName": "St Albans",
    "alpTpp2022": 59.564340911636236,
    "coalitionTpp2022": 40.43565908836376,
    "tppFormalVotes2022": 35716,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 64,
        "alpEnd": 67.4971122545416,
        "alpSwing": 3.497112254541601,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 67.4971122545416,
        "alpEnd": 71.5360995625119,
        "alpSwing": 4.038987307970288,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 72,
        "alpEnd": 59.564340911636236,
        "alpSwing": -12.435659088363764,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "sunbury",
    "districtName": "Sunbury",
    "alpTpp2022": 56.412772503049915,
    "coalitionTpp2022": 43.587227496950085,
    "tppFormalVotes2022": 37706,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 56.49999999999999,
        "alpEnd": 54.296190450513606,
        "alpSwing": -2.2038095494863907,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 54.296190450513606,
        "alpEnd": 64.33035829110831,
        "alpSwing": 10.03416784059471,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 64.5,
        "alpEnd": 56.412772503049915,
        "alpSwing": -8.087227496950085,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "sydenham",
    "districtName": "Sydenham",
    "alpTpp2022": 58.7275879374059,
    "coalitionTpp2022": 41.27241206259409,
    "tppFormalVotes2022": 43838,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 61.5,
        "alpEnd": 66.25771507746569,
        "alpSwing": 4.757715077465696,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 66.25771507746569,
        "alpEnd": 67.86090128855733,
        "alpSwing": 1.603186211091634,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 68.3,
        "alpEnd": 58.7275879374059,
        "alpSwing": -9.572412062594097,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "tarneit",
    "districtName": "Tarneit",
    "alpTpp2022": 62.577802822673604,
    "coalitionTpp2022": 37.422197177326396,
    "tppFormalVotes2022": 39041,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 67.4,
        "alpEnd": 62.470000000000006,
        "alpSwing": -4.9300000000000015,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 62.46655381423033,
        "alpEnd": 61.13011650438984,
        "alpSwing": -1.336437309840488,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 61,
        "alpEnd": 64.580769436567,
        "alpSwing": 3.5807694365669995,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 64.580769436567,
        "alpEnd": 68.02228412256267,
        "alpSwing": 3.4415146859956725,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 67.9,
        "alpEnd": 62.577802822673604,
        "alpSwing": -5.322197177326402,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "thomastown",
    "districtName": "Thomastown",
    "alpTpp2022": 65.99577121751466,
    "coalitionTpp2022": 34.00422878248535,
    "tppFormalVotes2022": 37363,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 81.74,
        "alpEnd": 81.07,
        "alpSwing": -0.6699999999999928,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 81.07271789582259,
        "alpEnd": 70.18578120518785,
        "alpSwing": -10.886936690634741,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 71.6,
        "alpEnd": 78.4337420419712,
        "alpSwing": 6.8337420419712025,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 78.4337420419712,
        "alpEnd": 77.18764487714418,
        "alpSwing": -1.2460971648270203,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 77.4,
        "alpEnd": 65.99577121751466,
        "alpSwing": -11.404228782485347,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "warrandyte",
    "districtName": "Warrandyte",
    "alpTpp2022": 45.84996009577015,
    "coalitionTpp2022": 54.15003990422985,
    "tppFormalVotes2022": 45108,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 43.65,
        "alpEnd": 41.01,
        "alpSwing": -2.6400000000000032,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 41.00691455388631,
        "alpEnd": 36.12850387043935,
        "alpSwing": -4.87841068344696,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 32.800000000000004,
        "alpEnd": 38.401821757582,
        "alpSwing": 5.601821757581998,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 38.401821757582,
        "alpEnd": 46.12053029102625,
        "alpSwing": 7.718708533444252,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 46.2,
        "alpEnd": 45.84996009577015,
        "alpSwing": -0.35003990422985254,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "wendouree",
    "districtName": "Wendouree",
    "alpTpp2022": 63.46122024442711,
    "coalitionTpp2022": 36.53877975557289,
    "tppFormalVotes2022": 42303,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 49.9,
        "alpEnd": 55.7895026559877,
        "alpSwing": 5.8895026559877,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 55.7895026559877,
        "alpEnd": 60.25797224282233,
        "alpSwing": 4.468469586834633,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 61,
        "alpEnd": 63.46122024442711,
        "alpSwing": 2.4612202444271105,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "werribee",
    "districtName": "Werribee",
    "alpTpp2022": 60.5012417008768,
    "coalitionTpp2022": 39.4987582991232,
    "tppFormalVotes2022": 39462,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2010–14",
        "alpStart": 61.4,
        "alpEnd": 65.6552452998109,
        "alpSwing": 4.255245299810905,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 65.6552452998109,
        "alpEnd": 62.55070666356614,
        "alpSwing": -3.104538636244769,
        "comparison": "Same boundaries"
      }
    ]
  },
  {
    "districtId": "williamstown",
    "districtName": "Williamstown",
    "alpTpp2022": 63.44229486324217,
    "coalitionTpp2022": 36.55770513675784,
    "tppFormalVotes2022": 38974,
    "tppMethod2022": "Preference distribution",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 75.71,
        "alpEnd": 74.25,
        "alpSwing": -1.4599999999999835,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 74.2502776749352,
        "alpEnd": 61.81534107658746,
        "alpSwing": -12.434936598347745,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 63.2,
        "alpEnd": 66.5398225798633,
        "alpSwing": 3.339822579863294,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 66.5398225798633,
        "alpEnd": 72.07254960706138,
        "alpSwing": 5.5327270271980815,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 69.9,
        "alpEnd": 63.44229486324217,
        "alpSwing": -6.457705136757838,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  },
  {
    "districtId": "yan-yean",
    "districtName": "Yan Yean",
    "alpTpp2022": 54.45046047970853,
    "coalitionTpp2022": 45.54953952029147,
    "tppFormalVotes2022": 39524,
    "tppMethod2022": "2CP",
    "cycles": [
      {
        "cycle": "2002–06",
        "alpStart": 59.53000000000001,
        "alpEnd": 57.91,
        "alpSwing": -1.6200000000000103,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2006–10",
        "alpStart": 57.91118948380891,
        "alpEnd": 54.101778050275904,
        "alpSwing": -3.8094114335330054,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2010–14",
        "alpStart": 49.9,
        "alpEnd": 53.653321536533205,
        "alpSwing": 3.753321536533205,
        "comparison": "Redistribution-adjusted"
      },
      {
        "cycle": "2014–18",
        "alpStart": 53.653321536533205,
        "alpEnd": 67.02618162614506,
        "alpSwing": 13.37286008961186,
        "comparison": "Same boundaries"
      },
      {
        "cycle": "2018–22",
        "alpStart": 66.9,
        "alpEnd": 54.45046047970853,
        "alpSwing": -12.449539520291474,
        "comparison": "Estimated on 2022 boundaries"
      }
    ]
  }
] as const;
