// Generated by scripts/check-release-readiness.mjs. Do not edit by hand.
export const releaseReadiness = {
  "schemaVersion": 1,
  "assessedAsOf": "2026-08-28",
  "status": "experimental-blocked",
  "policy": "retain-last-valid-forecast",
  "automation": {
    "scheduledMonitoring": true,
    "automaticProductionPublish": false
  },
  "gates": {
    "sourceIntegrity": {
      "passed": true,
      "label": "Source fingerprints match"
    },
    "criticalSourceFreshness": {
      "passed": true,
      "label": "Critical sources are within policy"
    },
    "deterministicOutputs": {
      "passed": true,
      "label": "Model outputs and configuration match"
    },
    "historicalValidation": {
      "passed": true,
      "label": "Four-cycle baseline ledger is present"
    },
    "productionAuthorisation": {
      "passed": false,
      "label": "Complete probability model authorised"
    }
  },
  "sources": [
    {
      "id": "vec-2022-district-results",
      "critical": true,
      "dataEffectiveDate": "2022-11-26",
      "ageDays": 1371,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "vec-2022-voting-centres",
      "critical": false,
      "dataEffectiveDate": "2022-11-26",
      "ageDays": 1371,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "vec-historical-boundary-estimates",
      "critical": true,
      "dataEffectiveDate": "2022-11-26",
      "ageDays": 1371,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "vec-2026-enrolment",
      "critical": true,
      "dataEffectiveDate": "2026-06-30",
      "ageDays": 59,
      "stalenessThresholdDays": 62,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "ebc-2021-boundaries",
      "critical": true,
      "dataEffectiveDate": "2022-11-01",
      "ageDays": 1396,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "aec-2022-geographic-vote-surface",
      "critical": false,
      "dataEffectiveDate": "2022-05-21",
      "ageDays": 1560,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "vic-2026-poll-registry",
      "critical": true,
      "dataEffectiveDate": "2026-08-07",
      "ageDays": 21,
      "stalenessThresholdDays": 21,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "vec-recent-by-elections",
      "critical": false,
      "dataEffectiveDate": "2025-02-08",
      "ageDays": 566,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    },
    {
      "id": "forecast-derived-outputs",
      "critical": true,
      "dataEffectiveDate": "2026-08-26",
      "ageDays": 2,
      "stalenessThresholdDays": null,
      "stale": false,
      "artifactsCurrent": true
    }
  ]
} as const;
