// Generated by scripts/generate-source-provenance.mjs. Do not edit by hand.
export const sourceProvenance = {
  "schemaVersion": 1,
  "registryReviewedAt": "2026-08-28T01:30:00Z",
  "summary": {
    "sourceGroups": 9,
    "officialSourceGroups": 7,
    "criticalSourceGroups": 6,
    "tracedArtifacts": 21,
    "automationStatus": "scheduled-freshness-monitoring"
  },
  "sources": [
    {
      "id": "vec-2022-district-results",
      "name": "VEC 2022 state election district results",
      "publisher": "Victorian Electoral Commission",
      "sourceType": "official-election-results",
      "confidence": "official",
      "useStatus": "accepted",
      "modelRole": "Lower House baseline, candidate evidence and preference structure",
      "canonicalUrl": "https://www.vec.vic.gov.au/results/state-election-results/2022-state-election-results/results-by-district",
      "dataEffectiveDate": "2022-11-26",
      "lastCheckedAt": "2026-08-28T00:45:00Z",
      "updateFrequency": "static",
      "stalenessThresholdDays": null,
      "criticalToForecast": true,
      "localArtifacts": [
        "model/data/processed/vec_2022_indicative_candidate_evidence.csv",
        "app/data.generated.ts"
      ],
      "notes": "Official election results remain the primary state-election anchor.",
      "artifacts": [
        {
          "path": "model/data/processed/vec_2022_indicative_candidate_evidence.csv",
          "sha256": "dde62cda12d969bff2d558b1250195f78b4e8c41de9a3f395030f041a8b543aa",
          "bytes": 104855,
          "records": 323
        },
        {
          "path": "app/data.generated.ts",
          "sha256": "d648940f25a1e5f65293f300028e1861f49c41b15053137383a52e3cb0a4f3ac",
          "bytes": 25466,
          "records": null
        }
      ]
    },
    {
      "id": "vec-2022-voting-centres",
      "name": "VEC 2022 ordinary voting-centre results",
      "publisher": "Victorian Electoral Commission",
      "sourceType": "official-voting-centre-results",
      "confidence": "official",
      "useStatus": "display-only",
      "modelRole": "Seat-profile evidence; not currently a central forecast input",
      "canonicalUrl": "https://www.vec.vic.gov.au/results/state-election-results/2022-state-election-results/results-by-district",
      "dataEffectiveDate": "2022-11-26",
      "lastCheckedAt": "2026-08-28T00:45:00Z",
      "updateFrequency": "static",
      "stalenessThresholdDays": null,
      "criticalToForecast": false,
      "localArtifacts": [
        "app/booth-data.generated.ts"
      ],
      "notes": "Contains 1,729 physical ordinary voting centres. Early, postal, absent and provisional vote modes are excluded from geographic booth comparisons.",
      "artifacts": [
        {
          "path": "app/booth-data.generated.ts",
          "sha256": "c7475f4f420bd22392f2deb99fd01c9a71d2e001d306b9dd37b7a638d8fdef2f",
          "bytes": 537752,
          "records": null
        }
      ]
    },
    {
      "id": "vec-historical-boundary-estimates",
      "name": "VEC historical results and 2018 estimates on 2022 boundaries",
      "publisher": "Victorian Electoral Commission",
      "sourceType": "official-historical-results",
      "confidence": "official",
      "useStatus": "validation-only",
      "modelRole": "Historical swing, boundary-aware comparison and backtesting",
      "canonicalUrl": "https://www.vec.vic.gov.au/about-us/publications/research/research-archive",
      "dataEffectiveDate": "2022-11-26",
      "lastCheckedAt": "2026-08-28T00:30:00Z",
      "updateFrequency": "static",
      "stalenessThresholdDays": null,
      "criticalToForecast": true,
      "localArtifacts": [
        "app/historical-data.generated.ts"
      ],
      "notes": "The 2018–22 comparison uses the VEC estimate of 2018 support on the 2022 boundaries; it is not presented as a raw booth count.",
      "artifacts": [
        {
          "path": "app/historical-data.generated.ts",
          "sha256": "cc2f3e9f610378cbcf6f0b58fd150b1966f3564340651563ef3d3c80a9685eb3",
          "bytes": 93161,
          "records": null
        }
      ]
    },
    {
      "id": "vec-2026-enrolment",
      "name": "VEC district and region enrolment statistics",
      "publisher": "Victorian Electoral Commission",
      "sourceType": "official-enrolment",
      "confidence": "official",
      "useStatus": "accepted",
      "modelRole": "District and Upper House region weighting",
      "canonicalUrl": "https://www.vec.vic.gov.au/enrolment/electoral-roll-statistics",
      "dataEffectiveDate": "2026-06-30",
      "lastCheckedAt": "2026-08-28T00:30:00Z",
      "updateFrequency": "monthly",
      "stalenessThresholdDays": 62,
      "criticalToForecast": true,
      "localArtifacts": [
        "model/data/processed/vec_enrolment_district_2026-06.csv",
        "model/data/processed/vec_enrolment_region_2026-06.csv"
      ],
      "notes": "The current model bundle uses the June 2026 district and region releases. A later automation phase will detect and validate newer releases before promotion.",
      "artifacts": [
        {
          "path": "model/data/processed/vec_enrolment_district_2026-06.csv",
          "sha256": "ce4af13b5082134d0b7fb165abf991e14b35f7a2b9e317ef7f87a3f662764b28",
          "bytes": 5109,
          "records": 88
        },
        {
          "path": "model/data/processed/vec_enrolment_region_2026-06.csv",
          "sha256": "1c0ae644efb45cd14044b5b69528cb3af7cd15166d1dcaabd1763bd9e5087f85",
          "bytes": 676,
          "records": 8
        }
      ]
    },
    {
      "id": "ebc-2021-boundaries",
      "name": "2021 Victorian state electoral redivision",
      "publisher": "Electoral Boundaries Commission Victoria",
      "sourceType": "official-boundaries",
      "confidence": "official",
      "useStatus": "accepted",
      "modelRole": "Current district identities and district-to-region membership",
      "canonicalUrl": "https://www.ebc.vic.gov.au/Past-Redivisions/Default.html",
      "dataEffectiveDate": "2022-11-01",
      "lastCheckedAt": "2026-08-28T00:30:00Z",
      "updateFrequency": "event-driven",
      "stalenessThresholdDays": null,
      "criticalToForecast": true,
      "localArtifacts": [
        "model/data/processed/district_region_membership_2026.csv"
      ],
      "notes": "The 2021 redivision took effect for the 2022 state election and defines the current 88-district, eight-region structure.",
      "artifacts": [
        {
          "path": "model/data/processed/district_region_membership_2026.csv",
          "sha256": "f815161b2d8d6aa0c028f01d4e2fbeb615057ff2e659f1d116d5c52af3a921d7",
          "bytes": 3312,
          "records": 88
        }
      ]
    },
    {
      "id": "aec-2022-geographic-vote-surface",
      "name": "AEC 2022 federal-election geographic vote surface",
      "publisher": "Australian Electoral Commission",
      "sourceType": "official-federal-results",
      "confidence": "official",
      "useStatus": "experimental",
      "modelRole": "Secondary local-pattern evidence with shrinkage toward the VEC baseline",
      "canonicalUrl": "https://www.aec.gov.au/Elections/federal_elections/2022/downloads.htm",
      "dataEffectiveDate": "2022-05-21",
      "lastCheckedAt": "2026-08-26T04:30:00Z",
      "updateFrequency": "static",
      "stalenessThresholdDays": null,
      "criticalToForecast": false,
      "localArtifacts": [
        "model/data/processed/aec_2022_state_district_party_surface_vic.csv.gz",
        "model/data/processed/aec_2022_state_region_party_surface_vic.csv.gz"
      ],
      "notes": "Federal voting patterns are contextual predictors, not substitutes for Victorian state-election results.",
      "artifacts": [
        {
          "path": "model/data/processed/aec_2022_state_district_party_surface_vic.csv.gz",
          "sha256": "1b65fc4f865925f0f8abdfa6adb12ee674357c0867f5f7a2b8bc46d56e8f223a",
          "bytes": 34274,
          "records": 950
        },
        {
          "path": "model/data/processed/aec_2022_state_region_party_surface_vic.csv.gz",
          "sha256": "94548a20f13b47707adb97004bca8059b30b95512d9dec17ae2b44c53d171549",
          "bytes": 4732,
          "records": 123
        }
      ]
    },
    {
      "id": "vic-2026-poll-registry",
      "name": "Victorian 2026 voting-intention poll registry",
      "publisher": "Multiple pollsters and publishers",
      "sourceType": "polling",
      "confidence": "primary-mixed",
      "useStatus": "experimental",
      "modelRole": "Statewide multi-party polling state and uncertainty",
      "canonicalUrl": "https://www.roymorgan.com/findings/10303-victorian-state-voting-intention-august-2026",
      "dataEffectiveDate": "2026-08-07",
      "lastCheckedAt": "2026-08-26T04:30:00Z",
      "updateFrequency": "weekly",
      "stalenessThresholdDays": 21,
      "criticalToForecast": true,
      "localArtifacts": [
        "model/data/processed/poll_events_seed.csv",
        "model/data/processed/poll_estimates_seed.csv",
        "model/data/processed/upper_house_region_poll_2026-08.csv",
        "app/poll-data.generated.ts"
      ],
      "notes": "Each poll retains its own source URL, verification state, vote base, questionnaire regime and model-eligibility flag. The Upper House regional estimates are partially verified and receive guarded weight because regional sample sizes were not reported. Roy Morgan is one input rather than the forecast.",
      "artifacts": [
        {
          "path": "model/data/processed/poll_events_seed.csv",
          "sha256": "8bf9fe10fc4839bea01341ee6a1e0a5d48d09084697c829b3ce62f95e38b5858",
          "bytes": 7091,
          "records": 13
        },
        {
          "path": "model/data/processed/poll_estimates_seed.csv",
          "sha256": "35ff2acb57606d66d28f09b79d4b1427e6f43af5387e15473d228def856bf43b",
          "bytes": 4018,
          "records": 62
        },
        {
          "path": "model/data/processed/upper_house_region_poll_2026-08.csv",
          "sha256": "3387d85815972fcb3420c7316856efe28520158608cce62a5a68b42fc3dfb3d1",
          "bytes": 2331,
          "records": 8
        },
        {
          "path": "app/poll-data.generated.ts",
          "sha256": "ae24d87fcbff710bac0dacfda920dd2799e1c700a7a954e2b0b0ed8f9aae1a95",
          "bytes": 8710,
          "records": null
        }
      ]
    },
    {
      "id": "vec-recent-by-elections",
      "name": "VEC recent state by-election and supplementary-election results",
      "publisher": "Victorian Electoral Commission",
      "sourceType": "official-by-election-results",
      "confidence": "official",
      "useStatus": "experimental",
      "modelRole": "Guarded local evidence for Prahran, Werribee and Narracan",
      "canonicalUrl": "https://www.vec.vic.gov.au/results/state-election-results/state-by-elections-timeline",
      "dataEffectiveDate": "2025-02-08",
      "lastCheckedAt": "2026-08-26T04:30:00Z",
      "updateFrequency": "event-driven",
      "stalenessThresholdDays": null,
      "criticalToForecast": false,
      "localArtifacts": [
        "model/data/seed/recent_state_by_elections.json"
      ],
      "notes": "Narracan's January 2023 supplementary result is handled separately. Its booth explorer remains an explicit tracked gap rather than being mixed with the ordinary 2022 acquisition.",
      "artifacts": [
        {
          "path": "model/data/seed/recent_state_by_elections.json",
          "sha256": "46e040ef205019ed565ac8df7386c956e36a529e31b407ee252552fcbaa8aad0",
          "bytes": 11302,
          "records": null
        }
      ]
    },
    {
      "id": "forecast-derived-outputs",
      "name": "Deterministic 2026 forecast outputs",
      "publisher": "Victorian Election Forecasting Laboratory",
      "sourceType": "derived-model-output",
      "confidence": "internal-derived",
      "useStatus": "derived",
      "modelRole": "Checksummed bridge from the seeded model run to the published dashboard",
      "canonicalUrl": "https://github.com/MusicOfScience/vic-election-2026",
      "dataEffectiveDate": "2026-08-26",
      "lastCheckedAt": "2026-08-28T01:30:00Z",
      "updateFrequency": "dependency-driven",
      "stalenessThresholdDays": null,
      "criticalToForecast": true,
      "localArtifacts": [
        "model/data/processed/experimental_forecast_2026.json",
        "model/data/processed/experimental_forecast_2026_districts.csv",
        "model/data/processed/experimental_forecast_2026_chamber.csv",
        "model/data/processed/experimental_forecast_2026_seat_distribution.csv",
        "model/data/processed/experimental_forecast_2026_council_regions.csv",
        "model/data/processed/experimental_forecast_2026_council.csv",
        "app/model-output.generated.ts"
      ],
      "notes": "Seeded outputs are regenerated only when dependencies change. Checksums prevent an old website bundle from being paired with newer model files.",
      "artifacts": [
        {
          "path": "model/data/processed/experimental_forecast_2026.json",
          "sha256": "abc915428fb521f32ab463cc76b8e15b9f18c21bb47b1efba593a5cf5f612d7d",
          "bytes": 6291,
          "records": null
        },
        {
          "path": "model/data/processed/experimental_forecast_2026_districts.csv",
          "sha256": "0908b755e60f6d67e9dd94f5c439c95077f13ec54b129e46ef380c9cb8c55834",
          "bytes": 38023,
          "records": 88
        },
        {
          "path": "model/data/processed/experimental_forecast_2026_chamber.csv",
          "sha256": "9c7580b68d27d0cacdad1d93d6265f26559ef5adb82eb28bff61e98bee34f4e8",
          "bytes": 266,
          "records": 5
        },
        {
          "path": "model/data/processed/experimental_forecast_2026_seat_distribution.csv",
          "sha256": "f2b5070563791c50fcdc74bf1a52009bc753fbfd676044208bb22e3892188ce3",
          "bytes": 762,
          "records": 89
        },
        {
          "path": "model/data/processed/experimental_forecast_2026_council_regions.csv",
          "sha256": "120f3f8d7c72fee48907f63f3ad875b833dd555e38e166d9064521df676f4c4c",
          "bytes": 4301,
          "records": 8
        },
        {
          "path": "model/data/processed/experimental_forecast_2026_council.csv",
          "sha256": "f0b8446e94172222998505d940d60067bb49ae48a828e68ca1f9f774614d4b85",
          "bytes": 264,
          "records": 5
        },
        {
          "path": "app/model-output.generated.ts",
          "sha256": "b686d09083c7484ac37978a7f8c5f413757aa47f7cfce8b1e8e30b5123c0b515",
          "bytes": 134418,
          "records": null
        }
      ]
    }
  ]
} as const;
